pet = input("Введите вид питомца:  ")
age_pet = input("Введите возраст питомца:  ")
name_pet = input("Введите имя питомца:  ")
print("Это", end=" ")
print(pet, end=" ")
print("ему/ей", end=" ")
print(age_pet, end=" ")
print("лет", end=" ")
print("его/её", end=" ")
print(name_pet)
